float32 dt_frame
float32 dt_jpeg_to_rgb
float32 dt_track_targets
float32 camera_f
float32 camera_u0
float32 camera_v0
int32 camera_w
int32 camera_h
int32 image_w
int32 image_h

# R_cam^imu
float32 cam_imu_rx
float32 cam_imu_ry
float32 cam_imu_rz

# T_cam/imu^imu
float32 cam_imu_tx
float32 cam_imu_ty
float32 cam_imu_tz

float32 r_g
float32 r_b
float32 r_n
float32 g_r
float32 g_b
float32 g_n

# R_imu^world
float32 imu_rx
float32 imu_ry
float32 imu_rz

# T_imu/world^world
float32 imu_tx
float32 imu_ty
float32 imu_tz
