int32 num_targets

float32[] u
float32[] v
float32[] u1
float32[] v1
float32[] u2
float32[] v2
float32[] x_gps
float32[] y_gps

float32[] u_hat
float32[] v_hat
float32[] x_hat
float32[] y_hat
float32[] dx_hat
float32[] dy_hat
int32[] unique_id
int32[] confidence

int32 num_detections

float32[] detection_u
float32[] detection_v
float32[] detection_u1
float32[] detection_v1
float32[] detection_u2
float32[] detection_v2
